---
title: "BcellEpitope_extraction"
author: "Natasha"
date: "2023-03-27"
output: html_document
---

```{r}
rm(list = ls())
```

```{r}
##Loading packages
library("tidyverse")
library("dplyr")
library('data.table')
library('tidyr')
```

```{r}
####Loading files to R
B_cell_first<-read.table("C:/Users/HP/Downloads/B-epitope-SEB1-50.tsv", header = TRUE,sep = "\t")
B_cell_second<-read.table("C:/Users/HP/Downloads/B-epitope-SEB50-100.tsv", header = TRUE,sep = "\t")
B_cell_third<-read.table("C:/Users/HP/Downloads/B-epitope-SEB100-150.tsv", header = TRUE,sep = "\t")
B_cell_fourth<-read.table("C:/Users/HP/Downloads/B-epitope-SEB150-200.tsv", header = TRUE,sep = "\t")
```



```{r}
##Rounding off the columns 
B_cell_first$Round_off<- round(B_cell_first$EpitopeProbability , digits = 1)
B_cell_second$Round_off<- round(B_cell_second$EpitopeProbability , digits = 1)
B_cell_thrid$Round_off<- round(B_cell_thrid$EpitopeProbability , digits = 1)
B_cell_fourth$Round_off<- round(B_cell_fourth$EpitopeProbability , digits = 1)

###Dropping a column
B_cell_first<-B_cell_first[,-c(5,9)]
B_cell_second<-B_cell_second[,-c(5,9)]
B_cell_thrid<-B_cell_thrid[,-c(5,9)]
B_cell_fourth<-B_cell_fourth[,-c(5,9)]
```

```{r}
####Extracting epitopes whose threshold is >=0.5
B_cell_first$Prediction[B_cell_first$Round_off==0.5] <-"Epitope" 
finalB_cell_first<-B_cell_first %>% drop_na()

B_cell_second$Prediction[B_cell_second$Round_off ==0.5] <-"Epitope" 
finalB_cell_second<-B_cell_second %>% drop_na()

B_cell_third$Prediction[B_cell_third$Round_off ==0.5] <-"Epitope" 
finalB_cell_third<-B_cell_third %>% drop_na()

B_cell_fourth$Prediction[B_cell_fourth$Round_off ==0.5] <-"Epitope" 
finalB_cell_fourth<-B_cell_fourth %>% drop_na()

```

```{r}
###Saving R objects of the epitope tables
saveRDS(finalB_cell_first, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/B_cell1.RDS")
saveRDS(finalB_cell_second, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/B_cell2.RDS")
saveRDS(finalB_cell_third, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/B_cell3.RDS")
saveRDS(finalB_cell_fourth, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/B_cell4.RDS")
```

```{r}
###Saving R image
save.image("C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/Bcell_extraction.RData")
```

