---
title: '    CTLEpitopes'
author: "natasha"
date: "2023-03-18"
output:
  pdf_document: default
  html_document: default
---
```{r}
rm(list= ls())

```

```{r}
###Trying to read an xls file ( this did not work the error was "unable to open file")
##install.packages("readxl")
library("readxl")
library(data.table)
##XlNetCTL<-as.data.table(read_excel(path = "C:/Users/HP/Downloads/NetCTLpan.xls"))

```





```{r}
library("tidyverse")
library("dplyr")
library('data.table')
############################# EXTRACTION OF CTL EPITOPES ##############################
###Epitopes were selected with the following codes, this was done based on the threshold column, ##epitopes whose threshold (X.Rank was <=1 were filtered as potential CTL epitopes, this was done ) The filtering is done based on the different allels used in the analysis.
##From the 10 alleles used the allele 6 was observed not have any epitopes that met the criteria of having a threshold of <=1.

##NetCTL<-fread("C:/Users/HP/OneDrive/Desktop/Epitope/NetCTLpan.csv")###This method does not rename the duplicate col like the read.csv file
NetCTL<- read.table("C:/Users/HP/Downloads/NetCTL.tsv",header = TRUE, sep = "\t") ###This method renamesduplicate col

##Allele1 X.Rank1
pro_epi1<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele1, X.Rank1)
pro_epi1$Prediction[pro_epi1$X.Rank1 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL1<-pro_epi1%>% filter(Prediction=="Epitope")
finalCTL1<-subset(predCTL1,X.Rank1<=1)

###Allele2 X.Rank2
pro_epi2<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele2, X.Rank2)
pro_epi2$Prediction[pro_epi2$X.Rank2 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL2<-pro_epi2%>% filter(Prediction=="Epitope")
finalCTL2<-subset(predCTL2,X.Rank2<=1)

###Allele3 X.Rank3
pro_epi3<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele3, X.Rank3)
pro_epi3$Prediction[pro_epi3$X.Rank3 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL3<-pro_epi3%>% filter(Prediction=="Epitope")
finalCTL3<-subset(predCTL3,X.Rank3<=1)

##Allele4 X.Rank4
pro_epi4<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele4, X.Rank4)
pro_epi4$Prediction[pro_epi4$X.Rank4 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL4<-pro_epi4%>% filter(Prediction=="Epitope")
finalCTL4<-subset(predCTL4,X.Rank4<=1)

###Allele5 X.Rank5
pro_epi5<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele5, X.Rank5)
pro_epi5$Prediction[pro_epi5$X.Rank5 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL5<-pro_epi5%>% filter(Prediction=="Epitope")
finalCTL5<-subset(predCTL5,X.Rank5<=1)    

##Allele6 X.Rank6
pro_epi6<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele6, X.Rank6)
pro_epi6$Prediction[pro_epi6$X.Rank6 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL6<-pro_epi6%>% filter(Prediction=="Epitope")
finalCTL6<-subset(predCTL6,X.Rank6<=1)

##Allele7 X.Rank7
pro_epi7<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele7, X.Rank7)
pro_epi7$Prediction[pro_epi7$X.Rank7 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL7<-pro_epi7%>% filter(Prediction=="Epitope")
finalCTL7<-subset(predCTL7,X.Rank7<=1)

##Allele8 X.Rank8
pro_epi8<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele8, X.Rank8)
pro_epi8$Prediction[pro_epi8$X.Rank8 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL8<-pro_epi8%>% filter(Prediction=="Epitope")
finalCTL8<-subset(predCTL8,X.Rank8<=1)

##Allele9 X.Rank9
pro_epi9<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele9, X.Rank9)
pro_epi9$Prediction[pro_epi9$X.Rank9 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL9<-pro_epi9%>% filter(Prediction=="Epitope")
finalCTL9<-subset(predCTL9,X.Rank9<=1)

##Allele10 X.Rank10
pro_epi10<-NetCTL%>%select(N,Sequence.Name,Peptide,Allele10, X.Rank10)
pro_epi10$Prediction[pro_epi10$X.Rank10 <=1 ] <-"Epitope"
##Adding an epitope column
predCTL10<-pro_epi10%>% filter(Prediction=="Epitope")
finalCTL10<-subset(predCTL10,X.Rank10<=1)




####Saving the results as objects
####Each extracted CTL epitope for the individual alleles were saved as R objects
saveRDS(finalCTL1, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL1.RDS")
saveRDS(finalCTL2, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL2.RDS")
saveRDS(finalCTL3, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL3.RDS")
saveRDS(finalCTL4, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL4.RDS")
saveRDS(finalCTL5, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL5.RDS")
saveRDS(finalCTL6, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL6.RDS")
saveRDS(finalCTL7, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL7.RDS")
saveRDS(finalCTL8, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL8.RDS")
saveRDS(finalCTL9, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL9.RDS")
saveRDS(finalCTL10, "C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL10.RDS")


####Sving the Rimage
save.image("C:/Users/HP/OneDrive/Desktop/rstudio/multiepitope_vaccine/CTL_etraction.RData")


```

